version: "3.7"
services:
  php:
    build:
      args:
        uid: ${APP_UID}
      context: ./
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    env_file:
      - .env
      - .env.local
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      TERM: xterm-256color
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./var/composer/:/home/app/.composer/
      - ./docker/php/bin/:/home/app/bin/
      - ./docker/php/.bashrc:/home/app/.bashrc
      - ./var/hist-php/:/home/app/bash/
      - ./var/hist-php/:/home/app/zsh/
      - ./var/www/.git/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    ports:
      - "59001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php

  adminer:
    image: adminer
    ports:
      - '59002:8080'
    restart: unless-stopped
    depends_on:
      - db

  node:
    build:
      args:
        uid: ${APP_UID}
      context: ./
      dockerfile: docker/node/Dockerfile
    env_file:
      - .env
      - .env.local
    environment:
      TERM: xterm-256color
    volumes:
      - ./:/var/www
      - ./var/yarn/:/home/node/.cache/yarn/
      - ./docker/node/.bashrc:/home/node/.bashrc
      - ./var/hist-node/:/home/node/bash/
      - ./var/hist-node/:/home/node/zsh/
      - ./var/www/.git/

  redis:
    image: "redis:6.2"
    command: "redis-server --appendonly yes"
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    links:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis:6379
    ports:
      - "59003:8081"
    depends_on:
      - redis
