version: "3.7"
services:
  app:
    build:
      args:
        user: vadym
        uid: 1000
      context: ./
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
#      - ./docker/php/conf:/usr/local/etc/php/conf.d
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    ports:
      - "59001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - app

  adminer:
    image: adminer
    ports:
      - '59002:8080'
    restart: unless-stopped
    links:
      - db
