version: "3.7"
services:
  php:
    build:
      args:
        user: vadym
        uid: 1000
      context: ./
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./var/composer/:/home/vadym/.composer/
      - ./var/www/.git/
    links:
      - db
      - redis

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    ports:
      - "59001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - php

  adminer:
    image: adminer
    ports:
      - '59002:8080'
    restart: unless-stopped
    links:
      - db

  node:
    image: node:16
    build:
      args:
        user: vadym
        uid: 1000
      context: ./
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/var/www
      - ./var/yarn/:/home/vadym/.cache/yarn/
      - ./var/www/.git/

  redis:
    image: "redis:6.2"
    command: "redis-server --appendonly yes"
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    links:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis:6379
    ports:
      - "59003:8081"
