# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Command\LintAnnotationCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\DataFixtures\FileFactory:
        arguments:
            $filesystem: '@oneup_flysystem.default_filesystem_filesystem'
            $mimeTypes: '@mime_types'

    App\DataFixtures\ClearUploadDirFixtures:
        arguments:
            $filesystem: '@oneup_flysystem.default_filesystem_filesystem'

    App\File\PublicUrlGenerator:
        arguments:
            $bucket: '%app.file.bucket%'

    Imgproxy\UrlBuilder:
        arguments:
            $baseUrl: '%env(IMGPROXY_BASE_URL)%'
            $key: '%env(IMGPROXY_KEY)%'
            $salt: '%env(IMGPROXY_SALT)%'

    App\Controller\SentryController:
        arguments:
            $client: '@eight_points_guzzle.client.test_client'
